import { arrayAdditionI } from "./easy/array-addition-i.js";
import { points } from "../codewars/8kyu/total-amount-of-points.js";
import { evenOrOdd } from "../codewars/8kyu/even-or-odd.js";
import { reversedString } from "../codewars/8kyu/reversed-string.js";
import { countSheeps } from "../codewars/8kyu/counting-sheep.js";
import { makeNegative } from "../codewars/8kyu/return-negative.js";
import { isDivisible } from "../codewars/8kyu/is-divisible.js";
import { century } from "../codewars/8kyu/century-from-year.js";
import { summation } from "../codewars/8kyu/grasshopper-summation.js";